from __future__ import annotations

import argparse
import csv
import json
import math
from collections import Counter, defaultdict
from pathlib import Path
from typing import Iterable


FOCUS_PREFIXES = ("ECx", "NOEC", "LOEC")
EVAL_SPLITS = {"test", "validation", "finetune_validation"}
REQUIRED_FILES = (
    "predictions.csv",
    "metrics.csv",
    "metrics_filtered.csv",
    "effect_level_metrics_filtered.csv",
    "split_medium_audit.csv",
    "history.csv",
    "manifest.json",
)


def main() -> None:
    parser = argparse.ArgumentParser(description="Summarize deep QSAR run directories.")
    parser.add_argument("--root", required=True, help="Root output directory containing */deep/*/*/predictions.csv")
    parser.add_argument("--out-dir", required=True, help="Directory for summary CSV files.")
    parser.add_argument("--run-times", default=None, help="Optional run_times CSV generated by matrix shell scripts.")
    args = parser.parse_args()

    root = Path(args.root)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    run_times = read_csv(Path(args.run_times)) if args.run_times else []
    time_by_run = {row.get("run_name", ""): row for row in run_times}

    focus_rows_out: list[dict[str, object]] = []
    family_rows: list[dict[str, object]] = []
    effect_rows: list[dict[str, object]] = []
    bin_rows: list[dict[str, object]] = []
    audit_rows: list[dict[str, object]] = []
    common_inputs: list[dict[str, object]] = []

    for pred_path in sorted(root.glob("*/deep/*/*/predictions.csv")):
        run_dir = pred_path.parent
        run_name = run_dir.parents[2].name
        split_name = run_dir.name
        rows = read_csv(pred_path)
        manifest = read_json(run_dir / "manifest.json")
        time_row = time_by_run.get(strip_version_prefix(run_name), time_by_run.get(run_name, {}))

        counts = Counter((row.get("split_part", ""), row.get("medium_domain", "")) for row in rows)
        aquatic_eval = sum(
            count
            for (split_part, medium), count in counts.items()
            if str(split_part) in EVAL_SPLITS and str(medium).lower() == "aquatic"
        )
        toxicity_manifest = manifest.get("toxicity_binning", {}) if isinstance(manifest.get("toxicity_binning", {}), dict) else {}
        source_manifest = manifest.get("source_weighting", {}) if isinstance(manifest.get("source_weighting", {}), dict) else {}
        audit_rows.append(
            {
                "run": strip_version_prefix(run_name),
                "run_dir_name": run_name,
                "split_name": split_name,
                "split_key": split_key(split_name),
                "required_files_present": all((run_dir / name).exists() for name in REQUIRED_FILES),
                "prediction_rows": len(rows),
                "prediction_medium_counts": json.dumps(
                    {f"{key[0]}|{key[1]}": value for key, value in sorted(counts.items())},
                    ensure_ascii=False,
                ),
                "aquatic_eval_rows": aquatic_eval,
                "best_epoch": manifest.get("best_epoch", ""),
                "epochs_ran": manifest.get("epochs_ran", ""),
                "source_weighting_applied": source_manifest.get("applied", ""),
                "source_weighting_method": source_manifest.get("method", ""),
                "source_weighting_alpha": source_manifest.get("alpha", ""),
                "source_proxy_distance_mean": source_manifest.get("proxy_distance_mean", ""),
                "effect_level_weighting_applied": nested_get(manifest, "effect_level_weighting", "applied"),
                "toxicity_binning_applied": toxicity_manifest.get("applied", ""),
                "toxicity_bin_eligible_samples": toxicity_manifest.get("eligible_samples", ""),
                "toxicity_bin_boundary_samples": toxicity_manifest.get("boundary_samples", ""),
                "toxicity_bin_conversion_counts": json.dumps(toxicity_manifest.get("conversion_counts", {}), ensure_ascii=False),
                "swa_enabled": nested_get(manifest, "swa", "enabled"),
                "duration_seconds": time_row.get("duration_seconds", ""),
                "exit_code": time_row.get("exit_code", ""),
            }
        )

        for split_part in sorted(EVAL_SPLITS):
            focus = focus_prediction_rows(rows, split_part=split_part)
            if focus:
                common_inputs.append(
                    {
                        "run": strip_version_prefix(run_name),
                        "split_name": split_name,
                        "split_key": split_key(split_name),
                        "prediction_split_part": split_part,
                        "rows": focus,
                    }
                )
                focus_rows_out.append(
                    {
                        "run": strip_version_prefix(run_name),
                        "split_name": split_name,
                        "split_key": split_key(split_name),
                        "prediction_split_part": split_part,
                        **metrics_from_prediction_rows(focus),
                    }
                )
            for family, sub in grouped(focus, lambda row: task_family(row)).items():
                family_rows.append(
                    {
                        "run": strip_version_prefix(run_name),
                        "split_name": split_name,
                        "prediction_split_part": split_part,
                        "task_family": family,
                        **metrics_from_prediction_rows(sub),
                    }
                )
            for (family, level), sub in grouped(
                focus,
                lambda row: (task_family(row), effect_level_label(row.get("effect_level_x", ""))),
            ).items():
                effect_rows.append(
                    {
                        "run": strip_version_prefix(run_name),
                        "split_name": split_name,
                        "prediction_split_part": split_part,
                        "task_family": family,
                        "effect_level_x": level,
                        **metrics_from_prediction_rows(sub),
                    }
                )
            for (status, label, boundary), sub in grouped(
                focus,
                lambda row: (
                    row.get("toxicity_bin_status", ""),
                    row.get("toxicity_bin_label", ""),
                    row.get("toxicity_bin_boundary_flag", ""),
                ),
            ).items():
                bin_rows.append(
                    {
                        "run": strip_version_prefix(run_name),
                        "split_name": split_name,
                        "prediction_split_part": split_part,
                        "toxicity_bin_status": status,
                        "toxicity_bin_label": label,
                        "toxicity_bin_boundary_flag": boundary,
                        **metrics_from_prediction_rows(sub),
                    }
                )

    write_csv(
        out_dir / "focus_summary.csv",
        focus_rows_out,
        ["run", "split_name", "split_key", "prediction_split_part", "n", "r2", "rmse", "mae", "huber_loss", "task_count", "tasks"],
    )
    write_csv(
        out_dir / "family_summary.csv",
        family_rows,
        ["run", "split_name", "prediction_split_part", "task_family", "n", "r2", "rmse", "mae", "huber_loss", "task_count", "tasks"],
    )
    write_csv(
        out_dir / "effect_level_summary.csv",
        effect_rows,
        ["run", "split_name", "prediction_split_part", "task_family", "effect_level_x", "n", "r2", "rmse", "mae", "huber_loss", "task_count", "tasks"],
    )
    write_csv(
        out_dir / "toxicity_bin_summary.csv",
        bin_rows,
        ["run", "split_name", "prediction_split_part", "toxicity_bin_status", "toxicity_bin_label", "toxicity_bin_boundary_flag", "n", "r2", "rmse", "mae", "huber_loss", "task_count", "tasks"],
    )
    write_csv(
        out_dir / "audit_summary.csv",
        audit_rows,
        [
            "run",
            "run_dir_name",
            "split_name",
            "split_key",
            "required_files_present",
            "prediction_rows",
            "prediction_medium_counts",
            "aquatic_eval_rows",
            "best_epoch",
            "epochs_ran",
            "source_weighting_applied",
            "source_weighting_method",
            "source_weighting_alpha",
            "source_proxy_distance_mean",
            "effect_level_weighting_applied",
            "toxicity_binning_applied",
            "toxicity_bin_eligible_samples",
            "toxicity_bin_boundary_samples",
            "toxicity_bin_conversion_counts",
            "swa_enabled",
            "duration_seconds",
            "exit_code",
        ],
    )
    write_csv(
        out_dir / "best_by_split.csv",
        best_by_split(focus_rows_out),
        ["split_key", "rank_metric", "rank", "run", "split_name", "prediction_split_part", "n", "r2", "rmse", "mae", "huber_loss", "task_count", "tasks"],
    )
    common_rows = common_task_summary(common_inputs)
    common_task_fieldnames = [
        "comparison_group",
        "prediction_split_part",
        "run",
        "split_name",
        "split_key",
        "n",
        "r2",
        "rmse",
        "mae",
        "huber_loss",
        "task_count",
        "tasks",
    ]
    write_csv(out_dir / "common_task_summary.csv", common_rows, common_task_fieldnames)
    write_csv(out_dir / "common_task_comparison.csv", common_rows, common_task_fieldnames)


def read_csv(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def read_json(path: Path) -> dict:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


def write_csv(path: Path, rows: list[dict[str, object]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def focus_prediction_rows(rows: list[dict[str, str]], *, split_part: str) -> list[dict[str, str]]:
    result = []
    for row in rows:
        if row.get("split_part") != split_part:
            continue
        if str(row.get("medium_domain", "soil")).lower() != "soil":
            continue
        task = row.get("task_head", "")
        if not task.startswith(FOCUS_PREFIXES):
            continue
        try:
            y_true = float(row["y_true"])
            y_pred = float(row["y_pred"])
        except Exception:
            continue
        if math.isfinite(y_true) and math.isfinite(y_pred):
            result.append(row)
    return result


def metrics_from_prediction_rows(rows: list[dict[str, str]]) -> dict[str, object]:
    y = [float(row["y_true"]) for row in rows]
    p = [float(row["y_pred"]) for row in rows]
    metrics = metrics_from_yp(y, p)
    tasks = sorted({row.get("task_head", "") for row in rows})
    metrics["task_count"] = len(tasks)
    metrics["tasks"] = ";".join(tasks)
    return metrics


def metrics_from_yp(y_true: list[float], y_pred: list[float]) -> dict[str, object]:
    n = len(y_true)
    if n == 0:
        return {"n": 0, "r2": "", "rmse": "", "mae": "", "huber_loss": ""}
    mean = sum(y_true) / n
    ss_res = sum((actual - predicted) ** 2 for actual, predicted in zip(y_true, y_pred))
    ss_tot = sum((actual - mean) ** 2 for actual in y_true)
    r2 = "" if ss_tot <= 0 else 1.0 - ss_res / ss_tot
    rmse = math.sqrt(ss_res / n)
    mae = sum(abs(actual - predicted) for actual, predicted in zip(y_true, y_pred)) / n
    huber = sum(huber_loss(actual - predicted) for actual, predicted in zip(y_true, y_pred)) / n
    return {"n": n, "r2": r2, "rmse": rmse, "mae": mae, "huber_loss": huber}


def huber_loss(error: float, delta: float = 1.0) -> float:
    abs_error = abs(error)
    return 0.5 * error * error if abs_error <= delta else delta * (abs_error - 0.5 * delta)


def grouped(rows: Iterable[dict[str, str]], key_fn) -> dict[object, list[dict[str, str]]]:
    output: dict[object, list[dict[str, str]]] = defaultdict(list)
    for row in rows:
        output[key_fn(row)].append(row)
    return output


def task_family(row: dict[str, str]) -> str:
    value = row.get("task_family", "")
    if value:
        return value
    return row.get("task_head", "").split("_", 1)[0]


def effect_level_label(value: object) -> str:
    text = str(value or "").strip()
    if not text:
        return "none"
    try:
        number = float(text)
    except ValueError:
        return text
    if not math.isfinite(number):
        return "none"
    if abs(number - round(number)) < 1e-9:
        return str(int(round(number)))
    return f"{number:g}"


def split_key(split_name: str) -> str:
    if split_name.endswith("_f10"):
        return "f10"
    if split_name.endswith("_f20"):
        return "f20"
    if split_name.endswith("_f50"):
        return "f50"
    if split_name.endswith("_f100"):
        return "f100"
    if split_name == "SoilPtoxQC2_C_chemical_holdout_8_2":
        return "fullC"
    return split_name


def strip_version_prefix(value: str) -> str:
    parts = value.split("_", 1)
    if parts and parts[0].startswith("v") and len(parts) == 2:
        return parts[1]
    return value


def nested_get(payload: dict, key: str, child: str) -> object:
    value = payload.get(key, {})
    return value.get(child, "") if isinstance(value, dict) else ""


def best_by_split(rows: list[dict[str, object]]) -> list[dict[str, object]]:
    output: list[dict[str, object]] = []
    test_rows = [row for row in rows if row.get("prediction_split_part") == "test"]
    for key in sorted({str(row.get("split_key", "")) for row in test_rows}):
        candidates = [row for row in test_rows if str(row.get("split_key", "")) == key and int(row.get("n", 0) or 0) > 0]
        for metric in ("mae", "rmse"):
            ranked = sorted(candidates, key=lambda row: float(row.get(metric, "inf") or "inf"))
            for rank, row in enumerate(ranked[:10], start=1):
                output.append({"split_key": key, "rank_metric": metric, "rank": rank, **row})
        ranked_r2 = sorted(candidates, key=lambda row: float(row.get("r2", "-inf") or "-inf"), reverse=True)
        for rank, row in enumerate(ranked_r2[:10], start=1):
            output.append({"split_key": key, "rank_metric": "r2", "rank": rank, **row})
    return output


def common_task_summary(inputs: list[dict[str, object]]) -> list[dict[str, object]]:
    output: list[dict[str, object]] = []
    filtered = [row for row in inputs if not str(row.get("run", "")).startswith("smoke_")]
    for split_part in sorted({str(row.get("prediction_split_part", "")) for row in filtered}):
        split_rows = [row for row in filtered if row.get("prediction_split_part") == split_part]
        groups: dict[str, list[dict[str, object]]] = {}
        for key in ("f20", "f50", "f100", "fullC"):
            members = [row for row in split_rows if row.get("split_key") == key]
            if len(members) >= 2:
                groups[key] = members
        fullc_f100 = [
            row
            for row in split_rows
            if row.get("split_key") == "fullC"
            or (row.get("split_key") == "f100" and str(row.get("run", "")).startswith("transfer_"))
        ]
        if any(row.get("split_key") == "fullC" for row in fullc_f100) and any(
            row.get("split_key") == "f100" for row in fullc_f100
        ):
            groups["fullC_vs_transfer_f100"] = fullc_f100

        for group_name, members in sorted(groups.items()):
            common_tasks = intersect_tasks(members)
            if not common_tasks:
                continue
            for member in members:
                rows = [row for row in member["rows"] if row.get("task_head", "") in common_tasks]  # type: ignore[index]
                if not rows:
                    continue
                output.append(
                    {
                        "comparison_group": group_name,
                        "prediction_split_part": split_part,
                        "run": member.get("run", ""),
                        "split_name": member.get("split_name", ""),
                        "split_key": member.get("split_key", ""),
                        **metrics_from_prediction_rows(rows),
                    }
                )
    return output


def intersect_tasks(members: list[dict[str, object]]) -> set[str]:
    task_sets: list[set[str]] = []
    for member in members:
        rows = member.get("rows", [])
        if not isinstance(rows, list):
            continue
        tasks = {str(row.get("task_head", "")) for row in rows if isinstance(row, dict) and row.get("task_head")}
        if tasks:
            task_sets.append(tasks)
    if not task_sets:
        return set()
    common = set.intersection(*task_sets)
    return set(common)


if __name__ == "__main__":
    main()
